version: '3.1'

services:

  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${USER_ONE}
      - N8N_BASIC_AUTH_PASSWORD=${PASS_ONE}
      - GENERIC_TIMEZONE
    ports:
      - ${PORT_ONE}:5678
    volumes:
      - ./${DATA_ONE}:/root/.n8n
    command: /bin/sh -c "sleep 1; n8n start"
